### DRQ-v2 Agent Base Configuration ###
agent:
  name: drqv2
  kwargs:
    lr: 1e-4
    critic_target_tau: 0.01
    num_expl_steps: 1000
    hidden_dim: 1024
    feature_dim: 50
    stddev_schedule: 'linear(0.5, 0.1, 100000)'
    stddev_clip: 0.3
    num_seed_frames: 1000
    update_every_steps: 10


### Off-Policy Buffer Configuration ###
buffer:
  kwargs:
    name: "off-policy"
    max_size:  1000000
    nstep: 3
    batch_size: 256
    fetch_every: 1000
    num_workers: 1
    save_snapshot: True
    discount: 0.99
