agent:
  name: drqv2
  kwargs:
    lr: 1e-4
    critic_target_tau: 0.01
    update_every_steps: 2
    num_expl_steps: 2000
    hidden_dim: 1024
    feature_dim: 50
    stddev_schedule: 'linear(1.0,0.1,500000)'
    stddev_clip: 0.3
