### DRQ-v2 Agent Base Configuration ###
agent:
  name: mae
  kwargs:
    lr: 1e-4
    critic_lr: 1e-4 # null
    encoder_lr: 5e-4
    critic_target_tau: 0.01 # 0.01 default
    num_expl_steps: 1000
    hidden_dim: 1024
    feature_dim: 50
    stddev_clip: 0.3
    num_seed_frames: 1000
    update_every_steps: 10
    log_std_init: null # exp(-.5) = .6 set to null to disable
    stddev_schedule:
      name: linear
      start: 1.0
      end: 0.1
      num_steps: 100000
    mask_strat: "all" # middle
    vit_dim: 512
    vit_depth: 2
    vit_heads: 8
    vit_mlp_dim: 512  # 2048
    vit_dropout: 0.0
    vit_emb_dropout: 0.0




### Off-Policy Buffer Configuration ###
buffer:
  kwargs:
    name: "off-policy"
    max_size:  1000000
    nstep: 3
    batch_size: 256
    fetch_every: 1000
    num_workers: 1
    save_snapshot: True
    discount: 0.99
