num_seed_frames: 1000

### MAE Agent Base Configuration ###
agent:
  cls: MAEAgent
  name: mae
  kwargs:
    lr: 1e-4
    critic_lr: 1e-4 # null
    model_lr: 1e-4
    critic_target_tau: 0.01 # 0.01 default
    num_expl_steps: 2000
    hidden_dim: 1024
    feature_dim: 50
    stddev_clip: 0.3
    update_every_steps: 2
    log_std_init: null # exp(-.5) = .6 set to null to disable
    weight_decay: 0.01
    use_actor_ln: True

    stddev_schedule:
      name: linear
      start: 1.0
      end: 0.1
      num_steps: 500000

decoder:
  cls: ViT
  kwargs:
    dim: 256 #64 * nheads
    depth: 1
    head_dim: 64
    heads: 4
    mlp_dim: 1024 # dim * 4


encoder:
  cls: ViT
  kwargs:
    dim: 64
    head_dim: 64
    depth: 1
    heads: 1
    mlp_dim: 128  # 2048
    dropout: 0.0
    emb_dropout: 0.0
    nonlinearity: "geglu"
    qkv_bias: False

tokenizer:
  cls: "SpatioTemporalTokenizer"
  kwargs:
    patch_size: 12

model:
  cls: "SequentialMaskedAutoEncoder"
  kwargs:
    use_last_ln: True


### Off-Policy Buffer Configuration ###
buffer:
  kwargs:
    buffer_type: "off-policy"
    max_size:  1000000
    nstep: 3
    batch_size: 256
    fetch_every: 1000
    num_workers: 1 #4
    save_snapshot: false
    discount: 0.99
