#checkpoint_every: 1
dataloader:
  batch_size: 10
  num_workers: 0
  shuffle: 'True'
#git_rev: ff7a0d50f5634b7cda393161db079e32dd21d1db
#log_wandb_every: 10
#max_num_samples: 1000
#num_epochs: 100
paths:
  rollouts: random-rollouts-50k/rollouts_e256_t200.hdf5
  vae_weights: experiments/vae/Weights/vae-20.pt
use_wandb: 'False'
#valid_every: 1
vae:
  latent: 32

lstm:
  input_size: 32
  output_size: 32
  lstm_layers: 2
  lstm_size: 128

num_epochs: 100
lr: 0.01

