### DRQ-v2 Agent Base Configuration ###
agent:
  name: drqv2
  kwargs:
    lr: 1e-4
    critic_lr: 1e-4 # null
    critic_target_tau: 0.01 # 0.01 default
    num_expl_steps: 2000
    hidden_dim: 1024
    feature_dim: 50
    stddev_clip: 0.3
    update_every_steps: 2
    log_std_init: null # exp(-.5) = .6 set to null to disable
    stddev_schedule:
      name: linear
      start: 1.0
      end: 0.1
      num_steps: 100000


### Off-Policy Buffer Configuration ###
buffer:
  kwargs:
    buffer_type: "off-policy"
    max_size:  1000000
    nstep: 3
    batch_size: 256
    fetch_every: 1000
    num_workers: 1
    save_snapshot: false
    discount: 0.99
