### SMAQ Agent Base Configuration ###
agent:
  cls: SMAQAgent
  name: smaq
  kwargs:
    lr: 1e-4
    critic_lr: 1e-3 # 1e-4
    model_lr: 1e-4
    critic_target_tau: 0.01 # 0.01 default
    model_target_tau: 0.01 # 0.01 default
    num_expl_steps: 2000
    hidden_dim: 1024
    feature_dim: 50
    stddev_clip: 0.3
    update_every_steps: 2
    log_std_init: null # exp(-.5) = .6 set to null to disable
    weight_decay: 0.01
    use_actor_ln: True
    use_model_ema: True
    use_q_approx_loss: False
    use_masked_state_loss: True
    use_drqv2_augs: True
    smaq_update_optim_step: True
    smaq_train_reconstruction: False
    stddev_schedule:
      name: linear
      start: 1.0
      end: 0.1
      num_steps: 100000

decoder:
  cls: ViT
  kwargs:
    dim: 256 #64 * nheads
    depth: 1
    head_dim: 64
    heads: 4
    gelu_mult: 4


encoder:
  cls: ViT
  kwargs:
    dim: 128
    head_dim: 64
    depth: 1
    heads: 1
    dropout: 0.0
    emb_dropout: 0.0
    gelu_mult: 4
    qkv_bias: False


tokenizer:
  cls: "SpatioTemporalTokenizer"
  kwargs:
    patch_size: 12
    pe_method: "vit-1d-pe"

model:
  cls: "SequentialMaskedAutoEncoder" # "VolumetricMaskedAutoEncoder"
  kwargs:
    use_last_ln: True
    use_cls_token: True
    auto_encoding_mask_type: hybrid-nfp-smaq-uniform # temporal-multinoulli, hybrid-nfp-multinoulli, nfp, smaq-uniform
    state_encoding_mask_type: "smaq-uniform"
    action_encoding_dim: 3
    masking_ratio: 0.75


### Off-Policy Buffer Configuration ###
buffer:
  kwargs:
    buffer_type: "off-policy"
    max_size:  1000000
    nstep: 3
    batch_size: 256
    fetch_every: 1000
    num_workers: 1 #4
    save_snapshot: false
    discount: .99
