wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.24
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      2:
      - 1
      3:
      - 1
      4: 3.7.7
      5: 0.10.24
      8:
      - 5
clip_ratio:
  desc: null
  value: 0.2
device:
  desc: null
  value: cpu
env_name:
  desc: null
  value: CartPole-v0
epochs:
  desc: null
  value: 50
gamma:
  desc: null
  value: 0.99
lam:
  desc: null
  value: 0.97
log_ep_freq:
  desc: null
  value: 10
max_ep_len:
  desc: null
  value: 1000
pi_lr:
  desc: null
  value: 0.0003
rew_smooth_len:
  desc: null
  value: 10
save_freq:
  desc: null
  value: 10
seed:
  desc: null
  value: 123
steps_per_epoch:
  desc: null
  value: 4000
target_kl:
  desc: null
  value: 0.01
train_pi_iters:
  desc: null
  value: 80
train_v_iters:
  desc: null
  value: 80
verbose:
  desc: null
  value: true
vf_lr:
  desc: null
  value: 0.001
