env:
  kwargs:
    name: dm-finger_spin
    max_ep_len: 1000 # (int): Maximum length of trajectory / episode / rollout. This is only used by some variable-length
    render_every: 25 # (int): Frequency at which to create a video of a rollout.
    action_repeat: 1
    frame_stack: 1
